# Generated by Django 3.1.7 on 2021-05-20 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='firstname',
        ),
        migrations.AddField(
            model_name='contact',
            name='lastname',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
    ]
